name: Continuous Deployment

on:
  workflow_run:
    workflows: ["dockerCheck"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no \
          -o BatchMode=yes root@${{ secrets.SERVER_IP }} "
            set -e
            cd /root/KIZAK
            git fetch origin main
            git reset --hard origin/main
            docker-compose down
            docker-compose up -d --build
          "
