name: dockerLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerLint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Back Dockerfile
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: back/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Front Dockerfile
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: front/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint ML Dockerfile
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: ml/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}