name: Docker-compose Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerCheck:
    timeout-minutes: 15
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run services
        run: docker compose up --build -d

      - name: Wait for services to become healthy
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat

          echo "Waiting for database..."
          timeout 60 bash -c 'until nc -z localhost 5432; do sleep 1; done'

          echo "Waiting for backend..."
          timeout 30 bash -c 'until nc -z localhost 8000; do sleep 1; done'
          
          echo "Testing backend..."
          curl --retry 5 --retry-delay 5 --retry-all-errors \
            --fail http://localhost:8000/health

          echo "Waiting for frontend..."
          timeout 30 bash -c 'until nc -z localhost 80; do sleep 1; done'
          
          echo "Testing frontend..."
          curl --retry 5 --retry-delay 5 --retry-all-errors \
            --fail http://localhost:80

      - name: Show logs if failed
        if: failure()
        run: docker compose logs

      - name: Stop containers
        if: always()
        run: docker compose down