name: Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies using Poetry
        working-directory: back
        run: |
          poetry install --no-root --no-interaction --no-ansi

      - name: pylint
        working-directory: back
        run: |
          poetry run pip install pylint
          poetry run pylint . --disable=C0114,C0115,C0116 --fail-under=5

      - name: Run tests
        working-directory: back
        run: |
          pytest
