name: API Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
      CORS_ORIGINS: http://localhost
      API_HOST: backend
      API_PORT: 8000
      FRONTEND_HOST: frontend
      FRONTEND_PORT: 3000
      FRONTEND_HOST_PORT: 3000
      POETRY_VIRTUALENVS_CREATE: false
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      MAIL_FROM: ${{secrets.MAIL_FROM}}
      MAIL_PORT: ${{secrets.MAIL_PORT}}
      MAIL_SERVER: ${{secrets.MAIL_SERVER}}
      MAIL_FROM_NAME: ${{secrets.MAIL_FROM_NAME}}
      DOMAIN: ${{secrets.DOMAIN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install dependencies
        working-directory: back
        run: poetry install --no-root

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U user -d db; do
            sleep 1
          done

      - name: Initialize database
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          PGPASSWORD="$DB_PASSWORD" psql -h localhost \
          -U "$DB_USER" -d "$DB_NAME" -f db/init.sql

      - name: Run tests
        working-directory: back
        run: poetry run pytest
