name: ty

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ty:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          python -m pip install -r requirements.txt

      - name: install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: ty
        run: |
          source .venv/bin/activate
          uvx ty check
