name: typos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typos:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.33.1
        with:
          ignore: |
            ml/jv_mapping.ipynb
            *.pb  # you can add more patterns here
