USER_SKILLS = (
    'sap', 'hibernate orm', 'телефонные переговоры', 'грамотная речь',
    'jquery', 'git', 'power bi', 'торговая площадка', '1c предприятие',
    'less', 'symfony', 'веб программирование', 'jira', 'sap sd',
    'деловая коммуникация', 'html', 'управление проектами', 'looker',
    'ssis', 'bash', 'разработка технических заданий', 'angularjs', 'ооп',
    'scikit learn', 'unix', 'tableau', 'pytorch', 'dhcp',
    '1с документооборот', 'numpy', 'powershell', 'soap', 'objective c',
    'alamofire', 'transact sql', 'shell', 'qlik', 'rest',
    'работа с базами данных', 'powerpoint', 'mongodb', 'ansible',
    'windows', 'gitlab', 'es6', 'outlook', '1с управление предприятием',
    'аналитические исследования', 'деловая переписка', 'entity framework',
    'realm', 'php5', 'django', 'аналитика', 'rxjava', 'flask', 'ajax',
    'js', 'mysql', 'confluence', '1с бухгалтерия', 'xcode', 'ms excel',
    'docker', 'spring boot', 'ms powerpoint', 'настройка пк', 'unity',
    'spring', 'viper', 'анализ данных', 'java ee', 'oracle pl sql',
    'uikit', 'api', 'zabbix', 'техническая поддержка', 'грамотность',
    'mvp', 'scrum', 'it', 'схемотехника электронного оборудования',
    'keras', 'yii2', 'sql', 'xml', 'субд', 'информационные технологии',
    'ssrs', 'python', 'android sdk', 'devops', 'alteryx', 'yii',
    'настройка dns', 'dynamodb', '1c бухгалтерия', 'mobx',
    'функциональное тестирование', 'информационная безопасность',
    'node.js', 'firebase', 'word', 'chef', 'reactjs', 'product management',
    'управление продуктом', 'pandas', 'django framework', 'ms visio',
    'test case', 'клиентоориентированность',
    '1с управление производственным предприятием',
    '1с комплексная автоматизация', 'linux', 'c', 'bitrix', 'bigquery',
    'mvc', 'java se', 'android', 'администрирование', 'uml', 'java',
    'администрирование сетевого оборудования', 'spss', 'системный анализ',
    'sql server', 'junit', 'sap erp', 'управление персоналом', 'c++',
    'jenkins', 'pyspark', 'деловое общение', 'scala', 'java core', 'css',
    'rabbitmq', '.net', 'системное мышление', 'r', 'бизнес анализ',
    'retrofit', 'scss', 'sap fi', 'ms sql server', 'cisco', 'css3',
    'html5', 'b2b продажи', 'javascript', 'tensorflow',
    'visual studio c#', 'тестирование', 'frontend', 'project management',
    'моделирование бизнес процессов', 'postgresql',
    'постановка задач разработчикам', 'ms project', 'apache maven',
    'swift', 'excel', 'работа в команде', 'visio', 'oracle', 'graphql',
    'bootstrap', 'sas', 'vba', 'gdpr', 'tcp ip', 'mvvm', 'английский язык',
    '1с битрикс', 'qa', 'пользователь пк', 'cocoapods', 'postman',
    'работа с большим объемом информации', 'redis', 'react', 'ремонт пк',
    'abap', '.net framework', 'github', 'ms sql', 'sharepoint',
    'active directory', '1с программирование', 'atlassian confluence',
    'kafka', 'windows server', 'matlab', 'kotlin', 'selenium',
    '1с управление торговлей', 'databricks', '1с предприятие', 'opencart',
    'bpmn', 'php7', 'terraform', 'laravel', 'spring framework',
    'техническое обслуживание', 'solid', 'php', 'puppet', 'snowflake',
    'настройка по', '.net core', 'azure', 'обновление конфигурации 1с',
    'redshift', 'typescript', 'redux', 'rx', 'atlassian jira', 'go',
    'регресcионное тестирование', 'кроссбраузерная верстка', 'spark',
    'тестирование пользовательского интерфейса', 'helpdesk',
    'администрирование серверов windows', 'golang',
    'аналитическое мышление', 't sql', 'nosql', 'ведение переговоров',
    'cassandra', 'webpack', 'ios', 'dagger', 'elasticsearch', 'sap mm',
    'asp.net', 'gcp', 'ruby', 'dax', 'настройка сетевых подключений',
    'организаторские навыки', 'erp системы на базе 1с', 'dagger2',
    'hadoop', 'rxswift', 'администрирование серверов linux', 'akka',
    'vue.js', 'оптимизация бизнес процессов', 'управление командой',
    'ci cd', '1с зарплата и управление персоналом', 'room', 'aws',
    'angular', 'проведение презентаций', 'kubernetes', 'mac os',
    'активные продажи', 'flow', 'cms wordpress', 'cats',
    'ориентация на результат', 'c#', 'airflow', 'autocad'
)
